### ISSUE TITLE
BUG: Toolbox Tries To Read The Path Of An Image That Doesn't Exist and Returns The Wrong Error

### ISSUE THREAD

**Issue by ghadjigeorghiou** [TissueImageAnalytics/tiatoolbox#288]
* TIA Toolbox version: 1.0.0
* Python version:3.9
* Operating System: Linux Debian (Docker Container)

### Description
I forgot to copy some jp2 and svs slide images in my Docker container. When I tried to create their thumbnails, for the images in the jp2 format I got an IndexError, while for the svs images I got an error from OpenSlide that the file is missing. I would expect for the jp2 formats (and all other formats) to get a similar error message, informing me what went wrong and how to fix it.

**Output for missing svs image**
```
Traceback (most recent call last):
  File "//read_image.py", line 4, in <module>
    wsi_reader_v1 = wsireader.get_wsireader(input_img='./test1.svs')
  File "/usr/local/lib/python3.9/site-packages/tiatoolbox/wsicore/wsireader.py", line 2417, in get_wsireader
    return WSIReader.open(input_img)
  File "/usr/local/lib/python3.9/site-packages/tiatoolbox/wsicore/wsireader.py", line 137, in open
    return OpenSlideWSIReader(input_img, mpp=mpp, power=power)
  File "/usr/local/lib/python3.9/site-packages/tiatoolbox/wsicore/wsireader.py", line 1346, in __init__
    self.openslide_wsi = openslide.OpenSlide(filename=str(self.input_path))
  File "/usr/local/lib/python3.9/site-packages/openslide/__init__.py", line 160, in __init__
    self._osr = lowlevel.open(filename)
  File "/usr/local/lib/python3.9/site-packages/openslide/lowlevel.py", line 128, in _check_open
    raise OpenSlideUnsupportedFormatError(
openslide.lowlevel.OpenSlideUnsupportedFormatError: Unsupported or missing image file
```

**Output from missing jp2 image**
```
Traceback (most recent call last):
  File "//read_image.py", line 13, in <module>
    wsi_info = wsi_reader_v1.info.as_dict()
  File "/usr/local/lib/python3.9/site-packages/tiatoolbox/wsicore/wsireader.py", line 190, in info
    self._m_info = self._info()
  File "/usr/local/lib/python3.9/site-packages/tiatoolbox/wsicore/wsireader.py", line 1718, in _info
    description = box[3].xml.find("description")
IndexError: list index out of range
```

**Comment by ghadjigeorghiou** [comment]
@shaneahmed No update. I haven't worked on it yet
