### ISSUE TITLE
Issue with DataLoader

### ISSUE THREAD

**Issue by spencerkrichevsky** [TissueImageAnalytics/tiatoolbox#502]
- TIA Toolbox version: 1.3.0
- Python version: 3.10.6
- Operating System: Linux 4.18.0-348.7.1.el8_5.x86_64

### Description

I'm trying to run the following code snippet from the tutorial posted here: https://github.com/TissueImageAnalytics/tiatoolbox/blob/develop/examples/full-pipelines/slide-graph.ipynb

```
if CACHE_PATH and os.path.exists(CACHE_PATH):
    SCALER_PATH = CACHE_PATH  # assignment for follow up loading
    node_scaler = joblib.load(SCALER_PATH)
else:
    # ! we need a better way of doing this, will have OOM problem
    loader = SlideGraphDataset(wsi_names, mode="infer")
    loader = DataLoader(
        loader, num_workers=8, batch_size=1, shuffle=False, drop_last=False
    )
    node_features = [v["graph"].x.numpy() for idx, v in enumerate(tqdm(loader))]
    node_features = np.concatenate(node_features, axis=0)
    node_scaler = StandardScaler(copy=False)
    node_scaler.fit(node_features)
    joblib.dump(node_scaler, SCALER_PATH)


# we must define the function after training/loading
def nodes_preproc_func(node_features):
    return node_scaler.transform(node_features)
```

This is my environment:

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
alabaster                 0.7.12                   pypi_0    pypi
albumentations            1.3.0                    pypi_0    pypi
anyio                     3.6.2                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
asciitree                 0.3.3                    pypi_0    pypi
asttokens                 2.0.8                    pypi_0    pypi
attrs                     22.1.0                   pypi_0    pypi
babel                     2.10.3                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.11.1                   pypi_0    pypi
blas                      1.0                         mkl
bleach                    5.0.1                    pypi_0    pypi
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2022.9.24            ha878542_0    conda-forge
cairo                     1.16.0               h19f5f5c_2
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1                   pypi_0    pypi
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
contourpy                 1.0.5                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
debugpy                   1.6.3                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
docutils                  0.19                     pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
executing                 1.1.1                    pypi_0    pypi
fasteners                 0.18                     pypi_0    pypi
fastjsonschema            2.16.2                   pypi_0    pypi
flask                     2.2.2                    pypi_0    pypi
fontconfig                2.13.1               h6c09931_0
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.11.0               h70c0345_0
gdk-pixbuf                2.42.8               h433bba3_0
glib                      2.69.1               h4ff587b_1
glymur                    0.11.7                   pypi_0    pypi
icu                       58.2                 he6710b0_3
idna                      3.4                      pypi_0    pypi
imagecodecs               2022.9.26                pypi_0    pypi
imageio                   2.22.2                   pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561
ipykernel                 6.16.1                   pypi_0    pypi
ipython                   8.5.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
itsdangerous              2.1.2                    pypi_0    pypi
jedi                      0.18.1                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
jpeg                      9e                   h7f8727e_0
json5                     0.9.10                   pypi_0    pypi
jsonschema                4.16.0                   pypi_0    pypi
jupyter-client            7.4.3                    pypi_0    pypi
jupyter-core              4.11.2                   pypi_0    pypi
jupyter-server            1.21.0                   pypi_0    pypi
jupyterlab                3.5.0                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-server         2.16.1                   pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1
lerc                      3.0                  h295c915_0
libdeflate                1.8                  h7f8727e_5
libffi                    3.3                  he6710b0_2
libgcc                    7.2.0                h69d50b8_2
libgcc-ng                 11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
libiconv                  1.17                 h166bdaf_0    conda-forge
libpng                    1.6.37               hbc83047_0
libstdcxx-ng              11.2.0               h1234567_1
libtiff                   4.4.0                hecacb30_0
libuuid                   1.0.3                h7f8727e_2
libwebp-base              1.2.4                h5eee18b_0
libxcb                    1.15                 h7f8727e_0
libxml2                   2.9.14               h74e7548_0
llvmlite                  0.39.1                   pypi_0    pypi
lxml                      4.9.1                    pypi_0    pypi
lz4-c                     1.9.3                h295c915_1
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.6.1                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mistune                   2.0.4                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640
mkl-fft                   1.3.1                    pypi_0    pypi
mkl-random                1.2.2                    pypi_0    pypi
mkl-service               2.4.0                    pypi_0    pypi
mkl_fft                   1.3.1           py310hd6ae3a3_0
mkl_random                1.2.2           py310h00e6091_0
nbclassic                 0.4.5                    pypi_0    pypi
nbclient                  0.7.0                    pypi_0    pypi
nbconvert                 7.2.2                    pypi_0    pypi
nbformat                  5.7.0                    pypi_0    pypi
ncurses                   6.3                  h5eee18b_3
nest-asyncio              1.5.6                    pypi_0    pypi
networkx                  2.8.7                    pypi_0    pypi
notebook                  6.5.1                    pypi_0    pypi
notebook-shim             0.2.0                    pypi_0    pypi
numba                     0.56.3                   pypi_0    pypi
numcodecs                 0.10.2                   pypi_0    pypi
numpy                     1.23.3                   pypi_0    pypi
numpy-base                1.23.3          py310h8e6c178_0
opencv-python             4.6.0.66                 pypi_0    pypi
opencv-python-headless    4.6.0.66                 pypi_0    pypi
openjpeg                  2.4.0                h3ad879b_0
openslide                 3.4.1                         2    bioconda
openslide-python          1.2.0                    pypi_0    pypi
openssl                   1.1.1q               h7f8727e_0
packaging                 21.3                     pypi_0    pypi
pandas                    1.5.1                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pcre                      8.45                 h295c915_0
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.2.0                    pypi_0    pypi
pip                       22.2.2                   pypi_0    pypi
pixman                    0.40.0               h7f8727e_1
prometheus-client         0.15.0                   pypi_0    pypi
prompt-toolkit            3.0.31                   pypi_0    pypi
psutil                    5.9.3                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pydicom                   2.3.0                    pypi_0    pypi
pygments                  2.13.0                   pypi_0    pypi
pynndescent               0.5.7                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyrsistent                0.18.1                   pypi_0    pypi
python                    3.10.6               haa1d7c7_1
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2022.5                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     24.0.1                   pypi_0    pypi
qudida                    0.0.4                    pypi_0    pypi
readline                  8.1.2                h7f8727e_1
requests                  2.28.1                   pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scikit-learn              1.1.2                    pypi_0    pypi
scipy                     1.9.3                    pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
setuptools                63.4.1                   pypi_0    pypi
shapely                   1.8.5.post1              pypi_0    pypi
simpleitk                 2.2.0                    pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1
sniffio                   1.3.0                    pypi_0    pypi
snowballstemmer           2.2.0                    pypi_0    pypi
soupsieve                 2.3.2.post1              pypi_0    pypi
sphinx                    5.3.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlite                    3.39.3               h5082296_0
stack-data                0.5.1                    pypi_0    pypi
terminado                 0.16.0                   pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tiatoolbox                1.3.0                    pypi_0    pypi
tifffile                  2022.10.10               pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0
tomli                     2.0.1                    pypi_0    pypi
torch                     1.12.1                   pypi_0    pypi
torch-geometric           2.1.0.post1              pypi_0    pypi
torch-scatter             2.0.9                    pypi_0    pypi
torch-sparse              0.6.15                   pypi_0    pypi
torchaudio                0.12.1                   pypi_0    pypi
torchvision               0.13.1                   pypi_0    pypi
tornado                   6.2                      pypi_0    pypi
tqdm                      4.64.1                   pypi_0    pypi
traitlets                 5.5.0                    pypi_0    pypi
typing-extensions         4.4.0                    pypi_0    pypi
tzdata                    2022e                h04d1e81_0
ujson                     5.5.0                    pypi_0    pypi
umap-learn                0.5.3                    pypi_0    pypi
urllib3                   1.26.12                  pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.4.1                    pypi_0    pypi
werkzeug                  2.2.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0
wsidicom                  0.4.0                    pypi_0    pypi
xz                        5.2.6                h5eee18b_0
zarr                      2.13.3                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0
zstd                      1.5.2                ha4553b6_0
```

I catch the following error:

```
Traceback (most recent call last):
  File "~/mutation_prediction/mutation_prediction.py", line 335, in <module>
    for idx, v in enumerate(tqdm(loader)):
  File "~/anaconda3/envs/mut_pred/lib/python3.10/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "~/anaconda3/envs/mut_pred/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "~/anaconda3/envs/mut_pred/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "~/anaconda3/envs/mut_pred/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "~/anaconda3/envs/mut_pred/lib/python3.10/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "~/anaconda3/envs/mut_pred/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "~/anaconda3/envs/mut_pred/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "~/anaconda3/envs/mut_pred/lib/python3.10/site-packages/torch_geometric/loader/dataloader.py", line 30, in __call__
    return {key: self([data[key] for data in batch]) for key in elem}
  File "~/anaconda3/envs/mut_pred/lib/python3.10/site-packages/torch_geometric/loader/dataloader.py", line 30, in <dictcomp>
    return {key: self([data[key] for data in batch]) for key in elem}
  File "~/anaconda3/envs/mut_pred/lib/python3.10/site-packages/torch_geometric/loader/dataloader.py", line 19, in __call__
    return Batch.from_data_list(batch, self.follow_batch,
  File "~/anaconda3/envs/mut_pred/lib/python3.10/site-packages/torch_geometric/data/batch.py", line 76, in from_data_list
    batch, slice_dict, inc_dict = collate(
  File "~/anaconda3/envs/mut_pred/lib/python3.10/site-packages/torch_geometric/data/collate.py", line 108, in collate
    out_store.batch = repeat_interleave(repeats, device=device)
  File "~/anaconda3/envs/mut_pred/lib/python3.10/site-packages/torch_geometric/data/collate.py", line 247, in repeat_interleave
    outs = [torch.full((n, ), i, device=device) for i, n in enumerate(repeats)]
  File "~/anaconda3/envs/mut_pred/lib/python3.10/site-packages/torch_geometric/data/collate.py", line 247, in <listcomp>
    outs = [torch.full((n, ), i, device=device) for i, n in enumerate(repeats)]
TypeError: full() received an invalid combination of arguments - got (tuple, int, device=NoneType), but expected one of:
 * (tuple of ints size, Number fill_value, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, Number fill_value, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
```

I believe the error pertains to this chunk of code:
```
from torch_geometric.data import Data, Dataset
from torch_geometric.loader import DataLoader
class SlideGraphDataset(Dataset):
    def __init__(self, info_list, mode="train", preproc=None):
        self.info_list = info_list
        self.mode = mode
        self.preproc = preproc
    def __getitem__(self, idx):
        info = self.info_list[idx]
        if any(v in self.mode for v in ["train", "valid"]):
            wsi_code, label = info
            # torch.Tensor will create 1-d vector not scalar
            label = torch.tensor(label)
        else:
            wsi_code = info
        with open(f"{GRAPH_DIR}/{wsi_code}.json", "r") as fptr:
            graph_dict = json.load(fptr)
        graph_dict = {k: np.array(v) for k, v in graph_dict.items()}
        if self.preproc is not None:
            graph_dict["x"] = self.preproc(graph_dict["x"])
        graph_dict = {k: torch.tensor(v) for k, v in graph_dict.items()}
        graph = Data(**graph_dict)
        if any(v in self.mode for v in ["train", "valid"]):
            return dict(graph=graph, label=label)
        return dict(graph=graph)
    def __len__(self):
        return len(self.info_list)
```

### What I Did

I re-installed torch_geometric and its version is: 2.1
I tried to see what is going wrong with DataLoader but I'm not sure how to resolve the issue.

All steps prior to this one seem to work well (i.e., dataset splitting, graph generation, feature extraction, etc.). Has anyone come across this?

**Comment by shaneahmed** [comment]
Please can you try version tiatoolbox version 1.0.1?

**Comment by spencerkrichevsky** [comment]
It turns out there's some bug with `torch_geometric.loader.DataLoader`. I omitted the batch step and manually coerce node_features to a tensor.

I changed this block:

```
if CACHE_PATH and os.path.exists(CACHE_PATH):
    SCALER_PATH = CACHE_PATH  # assignment for follow up loading
    node_scaler = joblib.load(SCALER_PATH)
else:
    # ! we need a better way of doing this, will have OOM problem
    loader = SlideGraphDataset(wsi_names, mode="infer")
    loader = DataLoader(
        loader, num_workers=8, batch_size=1, shuffle=False, drop_last=False
    )
    node_features = [v["graph"].x.numpy() for idx, v in enumerate(tqdm(loader))]
    node_features = np.concatenate(node_features, axis=0)
    node_scaler = StandardScaler(copy=False)
    node_scaler.fit(node_features)
    joblib.dump(node_scaler, SCALER_PATH)


# we must define the function after training/loading
def nodes_preproc_func(node_features):
    return node_scaler.transform(node_features)
```

to: 

```
if CACHE_PATH and os.path.exists(CACHE_PATH):
    SCALER_PATH = CACHE_PATH  # assignment for follow up loading
    node_scaler = joblib.load(SCALER_PATH)
else:
    loader = SlideGraphDataset(wsi_names, mode="infer")
    node_features = [torch.tensor(v["graph"].x) for idx, v in enumerate(tqdm(loader))]
    node_features = np.concatenate(node_features, axis=0)
    node_scaler = StandardScaler(copy=False)
    node_scaler.fit(node_features)
    joblib.dump(node_scaler, SCALER_PATH)
def nodes_preproc_func(node_features):
    return node_scaler.transform(node_features)
```
