### ISSUE TITLE
ValueError: MPP is None, when using SlidingWindowPatchExtractor class!

### ISSUE THREAD

**Issue by mrahimpour** [TissueImageAnalytics/tiatoolbox#534]
- TIA Toolbox version:  1.3.1
- Python version: 3.10.8
- Operating System: Ubuntu 22.04.1

### Description
I am using SlidingWindowPatchExtractor class to do the patch extraction. The WSI is read in the original resolution, but the tissue mask containing the regions that we want to extract the patches from WSI is generated on the downsampled image (resolution = 1 micron). To make sure that the metadata of the tissue mask has the required metadata, I defined the mask_metadata and open the mask with this info. However, when performing the patch extraction I got the value error stating the MPP is None.

### Here is the code
```
from tiatoolbox.tools.patchextraction import SlidingWindowPatchExtractor
from tiatoolbox.wsicore.wsireader import WSIReader, WSIMeta

working_resolution = 0.25
wsi_file = "./NSCLC_raw_data/NSCLC_001/H22-110_01_Scan1.tiff" # WSI with the maximum resolution of 0.25 micron
wsi_reader = WSIReader.open(input_img=wsi_file)
wsi_npy = wsi_reader.slide_thumbnail(resolution=working_resolution, units="mpp")
 
mask_file = "./NSCLC_raw_data/NSCLC_001/NSCLC_001.tiff"  # the tissue mask, resolution = 1 micron
mask_metadata = WSIMeta(slide_dimensions=(7920, 11340),
                        axes='YXS',
                        level_dimensions=[(7920, 11340)],
                        objective_power=10.0,
                        level_count=1,
                        level_downsamples=[8.0],
                        mpp=(1.0, 1.0),
                        )

mask_reader = WSIReader.open(input_img=mask_file, info=mask_metadata)

patch_size = (256, 256)
stride = (200, 200)
# print(mask_reader.info.as_dict())
patch_extractor = SlidingWindowPatchExtractor(
            input_img=wsi_npy,
            patch_size=patch_size,
            stride=stride,
            input_mask=mask_reader,
            resolution=working_resolution,
            units="mpp")
```
### here are the Trackbacks:

Traceback (most recent call last):
  File "../TissueImageAnalysis/patchExtractiontest.py", line 45, in <module>
    patch_extractor = SlidingWindowPatchExtractor(
  File "../miniconda3/envs/tiatoolbox-dev/lib/python3.10/site-packages/tiatoolbox/tools/patchextraction.py", line 618, in __init__
    self._generate_location_df()
  File "../miniconda3/envs/tiatoolbox-dev/lib/python3.10/site-packages/tiatoolbox/tools/patchextraction.py", line 195, in _generate_location_df
    slide_dimension = self.wsi.slide_dimensions(self.resolution, self.units)
  File "../miniconda3/envs/tiatoolbox-dev/lib/python3.10/site-packages/tiatoolbox/wsicore/wsireader.py", line 652, in slide_dimensions
    (_, _, wsi_shape_at_resolution, _,) = self._find_read_bounds_params(
  File "../miniconda3/envs/tiatoolbox-dev/lib/python3.10/site-packages/tiatoolbox/wsicore/wsireader.py", line 694, in _find_read_bounds_params
    read_level, post_read_scale_factor = self._find_optimal_level_and_downsample(
  File "../miniconda3/envs/tiatoolbox-dev/lib/python3.10/site-packages/tiatoolbox/wsicore/wsireader.py", line 404, in _find_optimal_level_and_downsample
    level_scales = self.info.relative_level_scales(resolution, units)
  File "../miniconda3/envs/tiatoolbox-dev/lib/python3.10/site-packages/tiatoolbox/wsicore/wsimeta.py", line 279, in relative_level_scales
    raise ValueError("MPP is None. Cannot determine scale in terms of MPP.")
ValueError: MPP is None. Cannot determine scale in terms of MPP.

**Comment by shaneahmed** [comment]
Your tiff image must be missing meta data. You can fix this by manually specifying mpp for the tiff image.

`wsi_reader = WSIReader.open(input_img=wsi_file, mpp=0.25)`

**Comment by mrahimpour** [comment]
Thanks a lot for the reply. 
The error is related to the mask_file, not the wsi_file. I also thought the metadata must be missing, this is why I generated the mask_metadata to make sure that all the metadata was available.

I followed your advice to manually specify the MPP:
'''
wsi_reader = WSIReader.open(input_img=wsi_file, mpp=0.25)
mask_reader = WSIReader.open(input_img=mask_file, mpp=1.0)
'''
And still, get the same error:
 **ValueError: MPP is None. Cannot determine scale in terms of MPP.**
