### ISSUE TITLE
🐛 Segmentation engines produce dictionary changed size during iteration error

### ISSUE THREAD

**Issue by shaneahmed** [TissueImageAnalytics/tiatoolbox#605]
- TIA Toolbox version: 1.4.0
- Python version: 3.8
- Operating System: Ubuntu (Google Colab)

### Description

[08-nucleus-instance-segmentation](https://github.com/TissueImageAnalytics/tiatoolbox/blob/develop/examples/08-nucleus-instance-segmentation.ipynb) and [09-multi-task-segmentation](https://github.com/TissueImageAnalytics/tiatoolbox/blob/develop/examples/09-multi-task-segmentation.ipynb) produces error on predict function in version 1.4.0. There is no error in the previous version.

![image](https://github.com/TissueImageAnalytics/tiatoolbox/assets/13048456/a1c5f457-dbba-4a4f-a520-1c911d97770a)

### What I Did

Ran the notebooks on Colab.

**Comment by shaneahmed** [comment]
Complete Error

```
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
RuntimeError: dictionary changed size during iteration
"""

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
[<ipython-input-8-84a593d2cd66>](https://localhost:8080/#) in <cell line: 12>()
     10 
     11 # WSI prediction (if ON_GPU=False, this part will take more than a couple of hours to process)
---> 12 wsi_output = inst_segmentor.predict(
     13     [wsi_file_name],
     14     masks=None,

6 frames
[/usr/local/lib/python3.10/dist-packages/tiatoolbox/models/engine/semantic_segmentor.py](https://localhost:8080/#) in predict(self, imgs, masks, mode, on_gpu, ioconfig, patch_input_shape, patch_output_shape, stride_shape, resolution, units, save_dir, crash_on_exception)
   1326         # => may not be able to retrieve the result dict
   1327         for wsi_idx, img_path in enumerate(imgs):
-> 1328             self._predict_wsi_handle_exception(
   1329                 imgs, wsi_idx, img_path, mode, ioconfig, save_dir, crash_on_exception
   1330             )

[/usr/local/lib/python3.10/dist-packages/tiatoolbox/models/engine/semantic_segmentor.py](https://localhost:8080/#) in _predict_wsi_handle_exception(self, imgs, wsi_idx, img_path, mode, ioconfig, save_dir, crash_on_exception)
   1178             wsi_save_path = save_dir.joinpath(f"{wsi_idx}")
   1179             if crash_on_exception:
-> 1180                 raise err
   1181             logging.error("Crashed on %s", wsi_save_path)
   1182 

[/usr/local/lib/python3.10/dist-packages/tiatoolbox/models/engine/semantic_segmentor.py](https://localhost:8080/#) in _predict_wsi_handle_exception(self, imgs, wsi_idx, img_path, mode, ioconfig, save_dir, crash_on_exception)
   1154         try:
   1155             wsi_save_path = save_dir.joinpath(f"{wsi_idx}")
-> 1156             self._predict_one_wsi(wsi_idx, ioconfig, str(wsi_save_path), mode)
   1157 
   1158             # Do not use dict with file name as key, because it can be

[/usr/local/lib/python3.10/dist-packages/tiatoolbox/models/engine/nucleus_instance_segmentor.py](https://localhost:8080/#) in _predict_one_wsi(self, wsi_idx, ioconfig, save_path, mode)
    735                 )
    736 
--> 737             self._merge_post_process_results()
    738         joblib.dump(self._wsi_inst_info, f"{save_path}.dat")
    739         # may need to chain it with parents

[/usr/local/lib/python3.10/dist-packages/tiatoolbox/models/engine/nucleus_instance_segmentor.py](https://localhost:8080/#) in _merge_post_process_results(self)
    782             # ! inferred tiles within this current WSI
    783             if future.exception() is not None:
--> 784                 raise future.exception()
    785 
    786             # aggregate the result via callback

[/usr/lib/python3.10/multiprocessing/queues.py](https://localhost:8080/#) in _feed(buffer, notempty, send_bytes, writelock, reader_close, writer_close, ignore_epipe, onerror, queue_sem)
    242 
    243                         # serialize the data before acquiring the lock
--> 244                         obj = _ForkingPickler.dumps(obj)
    245                         if wacquire is None:
    246                             send_bytes(obj)

[/usr/lib/python3.10/multiprocessing/reduction.py](https://localhost:8080/#) in dumps(cls, obj, protocol)
     49     def dumps(cls, obj, protocol=None):
     50         buf = io.BytesIO()
---> 51         cls(buf, protocol).dump(obj)
     52         return buf.getbuffer()
     53 

RuntimeError: dictionary changed size during iteration
```

**Comment by shaneahmed** [comment]
Runs fine locally on a Windows 11 Anaconda environment.

**Comment by shaneahmed** [comment]
#626 fixes the error however, [09-multi-task-segmentation](https://github.com/TissueImageAnalytics/tiatoolbox/blob/develop/examples/09-multi-task-segmentation.ipynb) fails to load tmp\\sample_tile_results\\0.raw.0.npy still fails which is not saved.
