### ISSUE TITLE
Issue in reading WSI with missing mpp information. 

### ISSUE THREAD

**Issue by engrodawood** [TissueImageAnalytics/tiatoolbox#628]
- TIA Toolbox version: 1.3.3
- Python version: 3.9.16
- Operating System: Linux

### Description

I am trying to use the segmentor class with a custom model.  The WSI I am passing does not have MPP information when open in QuPath but objective power and other information are there.  I have another version of tiatoolbox-1.3.0, it works fine but in the currect version it fails to process the WSI.  Example wsi can be downloaded from here: https://drive.google.com/file/d/14RqZQrahtWgMxFrTJDImJfcxOti3VGl0/view?usp=sharing

### What I Did

```
Traceback (most recent call last):
  File "/home/u1880906/cloud_workspace/PanCancerAnalysis/CPathPipeline/tissue_to_features/infer.py", line 116, in <module>
    wsi_segment_mapping = segmentor.predict(
  File "/opt/conda/envs/tiatoolbox-gpu/lib/python3.9/site-packages/tiatoolbox/models/engine/semantic_segmentor.py", line 1327, in predict
    self._predict_wsi_handle_exception(
  File "/opt/conda/envs/tiatoolbox-gpu/lib/python3.9/site-packages/tiatoolbox/models/engine/semantic_segmentor.py", line 1179, in _predict_wsi_handle_exception
    raise err
  File "/opt/conda/envs/tiatoolbox-gpu/lib/python3.9/site-packages/tiatoolbox/models/engine/semantic_segmentor.py", line 1155, in _predict_wsi_handle_exception
    self._predict_one_wsi(wsi_idx, ioconfig, str(wsi_save_path), mode)
  File "/opt/conda/envs/tiatoolbox-gpu/lib/python3.9/site-packages/tiatoolbox/models/engine/semantic_segmentor.py", line 724, in _predict_one_wsi
    wsi_proc_shape = wsi_reader.slide_dimensions(**resolution)
  File "/opt/conda/envs/tiatoolbox-gpu/lib/python3.9/site-packages/tiatoolbox/wsicore/wsireader.py", line 652, in slide_dimensions
    (_, _, wsi_shape_at_resolution, _,) = self._find_read_bounds_params(
  File "/opt/conda/envs/tiatoolbox-gpu/lib/python3.9/site-packages/tiatoolbox/wsicore/wsireader.py", line 694, in _find_read_bounds_params
    read_level, post_read_scale_factor = self._find_optimal_level_and_downsample(
  File "/opt/conda/envs/tiatoolbox-gpu/lib/python3.9/site-packages/tiatoolbox/wsicore/wsireader.py", line 404, in _find_optimal_level_and_downsample
    level_scales = self.info.relative_level_scales(resolution, units)
  File "/opt/conda/envs/tiatoolbox-gpu/lib/python3.9/site-packages/tiatoolbox/wsicore/wsimeta.py", line 277, in relative_level_scales
    raise ValueError("MPP is None. Cannot determine scale in terms of MPP.")
ValueError: MPP is None. Cannot determine scale in terms of MPP.
```

**Comment by shaneahmed** [comment]
When `mpp` is missing but `objective power` is provided then the toolbox infers mpp with a warning. https://github.com/TissueImageAnalytics/tiatoolbox/blob/d0d4ed62b591241319c8e6f74e84cc261a00536f/tiatoolbox/utils/misc.py#L289
Have you tried to debug if the toolbox is able to read objective power?

**Comment by engrodawood** [comment]
OK, thank you.
