### ISSUE TITLE
AttributeError: 'IOSegmentorConfig' object has no attribute 'margin'

### ISSUE THREAD

**Issue by alevangel** [TissueImageAnalytics/tiatoolbox#773]
- TIA Toolbox version: 1.5.1
- Python version: 3.8
- Operating System: Windows

### Description
I get this error, when trying to perform predict() for Necleus Istance segmentation:
```
|2024-01-22|09:10:30.167| [WARNING] Unknown scale (no objective_power or mpp)
Traceback (most recent call last):
  File "C:\Users\alevangeli\Anaconda3\envs\dpathology\lib\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-5d02148da079>", line 1, in <module>
    tile_output = inst_segmentor.predict(
  File "C:\Users\alevangeli\AppData\Roaming\Python\Python38\site-packages\tiatoolbox\models\engine\semantic_segmentor.py", line 1399, in predict
    self._predict_wsi_handle_exception(
  File "C:\Users\alevangeli\AppData\Roaming\Python\Python38\site-packages\tiatoolbox\models\engine\semantic_segmentor.py", line 1249, in _predict_wsi_handle_exception
    raise err  # noqa: TRY201
  File "C:\Users\alevangeli\AppData\Roaming\Python\Python38\site-packages\tiatoolbox\models\engine\semantic_segmentor.py", line 1225, in _predict_wsi_handle_exception
    self._predict_one_wsi(wsi_idx, ioconfig, str(wsi_save_path), mode)
  File "C:\Users\alevangeli\AppData\Roaming\Python\Python38\site-packages\tiatoolbox\models\engine\nucleus_instance_segmentor.py", line 714, in _predict_one_wsi
    tile_info_sets = self._get_tile_info(wsi_proc_shape, ioconfig)
  File "C:\Users\alevangeli\AppData\Roaming\Python\Python38\site-packages\tiatoolbox\models\engine\nucleus_instance_segmentor.py", line 445, in _get_tile_info
    margin = np.array(ioconfig.margin)
AttributeError: 'IOSegmentorConfig' object has no attribute 'margin'
```

### What I Did
This is the input, the file is .tiff extension:
```
    ioconfig = IOSegmentorConfig(
        input_resolutions=[
            {"units": "baseline", "resolution": 1.0},
        ],
        output_resolutions=[
            {"units": "baseline", "resolution": 1.0},
        ],
        patch_input_shape=(512, 512),
        patch_output_shape=(512, 512),
        stride_shape=(512, 512),
    )

    inst_segmentor = NucleusInstanceSegmentor(
        pretrained_model="hovernet_fast-pannuke",
        num_loader_workers=2,
        num_postproc_workers=2,
        batch_size=4,
    )

    tile_output = inst_segmentor.predict(
        [file_path],
        save_dir="sample_tile_results/",
        mode="wsi",  #wsi, tile
        on_gpu=False,
        crash_on_exception=True,
        patch_input_shape=(512, 512),
        units="baseline",
        resolution=1,
        ioconfig=ioconfig,
    )
```

**Comment by shaneahmed** [comment]
If you are doing semantic segmentation you should use [SemanticSegmentor](https://tia-toolbox.readthedocs.io/en/latest/_autosummary/tiatoolbox.models.engine.semantic_segmentor.SemanticSegmentor.html#tiatoolbox.models.engine.semantic_segmentor.SemanticSegmentor) engine.

If you would like to use [NucleusInstanceSegmentor](https://tia-toolbox.readthedocs.io/en/latest/_autosummary/tiatoolbox.models.engine.nucleus_instance_segmentor.NucleusInstanceSegmentor.html#tiatoolbox.models.engine.nucleus_instance_segmentor.NucleusInstanceSegmentor) then you should specify the [margin](https://github.com/TissueImageAnalytics/tiatoolbox/blob/000296305aa1faee5c95bac67ff37a23012ea53e/tiatoolbox/models/engine/nucleus_instance_segmentor.py#L41). You can specify the same margin of 128 as used in [HoVerNet IOConfig](https://github.com/TissueImageAnalytics/tiatoolbox/blob/b737f0b2c6b6737db370b7d88ea35576555a0504/tiatoolbox/data/pretrained_model.yaml#L639).

**Comment by shaneahmed** [comment]
I am closing this issue. Please feel free to reopen the issue if the above comment does not answer your question.
